### ISSUE TITLE
does not seem to acknoledge that /js is on a server

### ISSUE THREAD

**Issue by USMP-lancer** [DeltaNedas/unit-factory#3]
i dont know why, simply doint work with it

**Comment by USMP-lancer** [comment]
simple says you egg that would desync no matter what

**Comment by deltanedas** [comment]
having /js on a server implies that you are an admin, which unit factory checks for.

**Comment by USMP-lancer** [comment]
> having /js on a server implies that you are an admin, which unit factory checks for.

there is a server that allows all users to use it but ok
